version: '3'

services:
  api:
    build:
      context: ./api
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - data:/data

volumes:
  data:
